version: '3'
services:
  postgres:
    ports:
      - 5432:5432
    image: 'postgres:14.3-alpine'
    env_file:
      - .env # configure postgres

  webapi:
    build:
      context: ./
    ports:
      - 8000:8000
    depends_on: 
      - postgres
    restart: on-failure:5
